import type { ApartmentDetail } from "../types/ApartmentDetail";

export const items: ApartmentDetail[] = [
  {
    id: "1-1",
    title: "1-комнатная квартира",
    area: 88,
    images: ["/images/apartment/room/1/1-xl.png", "/images/apartment/room/1/1-1.png"],
    floor: 1,
    maxFloor: 12,
    height: 2.7,
    description: "Квартира имеет удачную планировку. Большие окна наполняют помещения естественным светом, создавая теплую атмосферу",
    rooms: ["Кухня", "Спальная Комната", "Ванная", "Коридор"],
  },
  {
    id: "1-2",
    title: "1-комнатная квартира",
    area: 53.86,
    images: ["/images/apartment/room/1/2-xl.png", "/images/apartment/room/1/2-1.png"],
    floor: 2,
    maxFloor: 12,
    height: 2.7,
    description: "Квартира имеет удачную планировку. Большие окна наполняют помещения естественным светом, создавая теплую атмосферу",
    rooms: ["Кухня", "Спальная Комната", "Ванная", "Коридор"],
  },
  {
    id: "1-3",
    title: "1-комнатная квартира",
    area: 72,
    images: ["/images/apartment/room/1/3-xl.png", "/images/apartment/room/1/3-1.png"],
    floor: 3,
    maxFloor: 12,
    height: 2.7,
    description: "Квартира имеет удачную планировку. Большие окна наполняют помещения естественным светом, создавая теплую атмосферу",
    rooms: ["Кухня", "Спальная Комната", "Ванная", "Коридор"],
  },
  {
    id: "2-1",
    title: "2-комнатная квартира",
    area: 88,
    images: ["/images/apartment/room/2/1-xl.png", "/images/apartment/room/2/1-1.png"],
    floor: 1,
    maxFloor: 12,
    height: 2.7,
    description: "Квартира имеет удачную планировку. Большие окна наполняют помещения естественным светом, создавая теплую атмосферу",
    rooms: ["Кухня", "Спальная Комната", "Ванная", "Коридор"],
  },
  {
    id: "2-2",
    title: "2-комнатная квартира",
    area: 53.86,
    images: ["/images/apartment/room/2/2-xl.png", "/images/apartment/room/2/2-1.png"],
    floor: 2,
    maxFloor: 12,
    height: 2.7,
    description: "Квартира имеет удачную планировку. Большие окна наполняют помещения естественным светом, создавая теплую атмосферу",
    rooms: ["Кухня", "Спальная Комната", "Ванная", "Коридор"],
  },
  {
    id: "2-3",
    title: "2-комнатная квартира",
    area: 72,
    images: ["/images/apartment/room/2/3-xl.png", "/images/apartment/room/2/3-1.png"],
    floor: 3,
    maxFloor: 12,
    height: 2.7,
    description: "Квартира имеет удачную планировку. Большие окна наполняют помещения естественным светом, создавая теплую атмосферу",
    rooms: ["Кухня", "Спальная Комната", "Ванная", "Коридор"],
  },
];
