/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * RCC
 * OpenAPI spec version: 1.0
 */

export type ContactMethod = typeof ContactMethod[keyof typeof ContactMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContactMethod = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
