/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * RCC
 * OpenAPI spec version: 1.0
 */

export interface CountryCodeResponse {
  /** @nullable */
  region?: string | null;
  /** @nullable */
  countryPhoneCode?: string | null;
  /** @nullable */
  countryName?: string | null;
  /** @nullable */
  mask?: string | null;
}
