/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * RCC
 * OpenAPI spec version: 1.0
 */
import type { Phone } from './phone';
import type { ContactMethod } from './contactMethod';

export interface SendContactRequest {
  /** @nullable */
  name?: string | null;
  phone?: Phone;
  contactMethod?: ContactMethod;
  /** @nullable */
  email?: string | null;
}
