/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * RCC
 * OpenAPI spec version: 1.0
 */

export interface SendContactResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
}
