name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - feature/sttcMdPm
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.prod.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: frontend.prod

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn
        working-directory: ./frontend

      - name: Build project
        run: yarn build
        working-directory: ./frontend

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/.next/*"
          target: "/var/rck/frontend"
