name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - feature/sttcMdPm
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.prod.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: frontend.prod

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn
        working-directory: ./frontend

      - name: Build project
        run: yarn build
        working-directory: ./frontend

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy using rsync
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./frontend/.next/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/rck/frontend/.next
